fix: better async handling
meateam/drive-ui pull request #107
Opened 2021-06-21 08:01 UTC by yoavrozner

Was not tested yet

2021-06-21 08:45 UTC, maya-fisher approved these changes
Looks good

2021-06-21 10:10 UTC, nettashviro requested changes
Very nice, but if you change it, please change the implementation in the 'files.js' file as well

2021-06-21 10:10 UTC, nettashviro commented on src/store/modules/transfer.js
> +                      getFileOwnerName(transferInfo.fileOwnerID),
Please do these functions separately.

2021-06-21 10:10 UTC, nettashviro commented on src/store/modules/transfer.js
> +          handleTransfers();
You can delete the else condition and put the 'handleTransfers' function outside the scope of the if

2021-06-22 07:07 UTC, yoavrozner commented on src/store/modules/transfer.js
> +                      getFileOwnerName(transferInfo.fileOwnerID),
Why???

2021-06-22 08:17 UTC, nettashviro commented on src/store/modules/transfer.js
> +                      getFileOwnerName(transferInfo.fileOwnerID),
These functions shouldn't be related in terms of their promise. 
first, you need to show the files and after that load the names of the owners. If for example the user-service has a timeout it will take a very long time to show all the files.

2021-06-22 08:18 UTC, nettashviro requested changes
please see my comments before.

2021-07-26 07:46 UTC, yoavrozner commented on src/store/modules/transfer.js
> +                      getFileOwnerName(transferInfo.fileOwnerID),
Done

2021-07-26 11:10 UTC, nettashviro approved these changes

2021-08-04 15:09 UTC, nettashviro approved these changes

2021-08-09 09:38 UTC, merged