fix: drag and drop files mime types
meateam/drive-ui pull request #108
Opened 2021-06-22 15:58 UTC by yoavrozner

2021-06-22 16:01 UTC, nettashviro approved these changes

2021-06-22 16:01 UTC, nettashviro commented on src/utils/drop.js
> +async function getFile(fileEntry) {
Please add docs

2021-06-22 16:02 UTC, nettashviro commented
Love that you've asked Yosef for pr

2021-06-23 07:02 UTC, yoavrozner commented on src/utils/drop.js
> +async function getFile(fileEntry) {
Good idea

2021-06-23 09:59 UTC, Shahar-Y requested changes

2021-06-23 09:59 UTC, Shahar-Y commented on src/utils/drop.js
> +async function getFile(fileEntry) {
Wa sthe documentation added?

2021-06-23 14:06 UTC, Shahar-Y approved these changes

2021-06-23 14:07 UTC, merged