hotfix - pageSize in shared with me
meateam/drive-ui pull request #119
Opened 2021-07-04 12:04 UTC by nettashviro

2021-07-04 15:21 UTC, Shahar-Y requested changes

2021-07-04 15:21 UTC, Shahar-Y commented on src/utils/getPageSize.js
> +export function getPageSize(fileView) {
The function logic is not clear. Add documentation.

2021-07-11 07:07 UTC, nettashviro commented on src/utils/getPageSize.js
> +export function getPageSize(fileView) {
done

2021-07-11 08:26 UTC, Shahar-Y approved these changes

2021-07-12 12:18 UTC, merged