Fix/shared files move
meateam/drive-ui pull request #126
Opened 2021-07-22 11:29 UTC by nettashviro

2021-07-26 11:39 UTC, yoavrozner requested changes
Well done!
Please see my notes

2021-07-26 11:39 UTC, yoavrozner commented on src/components/popups/MoveToPopup.vue
> +          : [this.$t("pageHeaders.SharedWithMe"), true];
Why isn't there external network breadcrumbs?

2021-07-26 11:39 UTC, yoavrozner commented on src/components/popups/MoveToPopup.vue
>        await this.fetchFolders(folder);
Promise.all

2021-07-26 11:42 UTC, nettashviro commented on src/components/popups/MoveToPopup.vue
> +          : [this.$t("pageHeaders.SharedWithMe"), true];
you can't move files from external networks

2021-08-01 07:18 UTC, nettashviro commented on src/components/popups/MoveToPopup.vue
>        await this.fetchFolders(folder);
done

2021-08-01 14:13 UTC, yoavrozner commented on src/components/popups/MoveToPopup.vue
> +          : [this.$t("pageHeaders.SharedWithMe"), true];
I used `getDriveFirstBreadcrumb` in File.vue. I think we should put it in the utils. What do you think?

2021-08-03 11:36 UTC, nettashviro commented on src/components/popups/MoveToPopup.vue
> +          : [this.$t("pageHeaders.SharedWithMe"), true];
we used this differently. what do you think?

2021-08-09 09:33 UTC, yoavrozner commented on src/components/popups/MoveToPopup.vue
> +          : [this.$t("pageHeaders.SharedWithMe"), true];
Ack

2021-08-09 09:34 UTC, yoavrozner approved these changes
GG WP

2021-08-09 09:35 UTC, merged