Feat/add copy clipboard
meateam/drive-ui pull request #145
Opened 2021-12-07 14:57 UTC by maya-fisher

2021-12-17 12:12 UTC, yarinBenisty approved these changes
All good!

2021-12-20 08:34 UTC, yoavrozner requested changes
Well done @maya-fisher !
Please see my comments

2021-12-20 08:34 UTC, yoavrozner commented on src/components/buttons/CopyToClipboardButton.vue
> +      else navigator.clipboard.writeText(`${window.location.origin}/file?id=${this.chosenFiles[0].id}`)
```suggestion
      const fileId = this.chosenFiles[0].id;
      if (isFolder(this.chosenFiles[0].type)) navigator.clipboard.writeText(`${window.location.origin}/folder?id=${fileId}`);
      else navigator.clipboard.writeText(`${window.location.origin}/file?id=${fileId}`)
```

2021-12-20 08:34 UTC, yoavrozner commented on src/components/buttons/CopyToClipboardButton.vue
> +    },
These functions belongs to the utils

2021-12-20 08:34 UTC, yoavrozner commented on src/i18n/he.json
> +    "CopyToClipboard": "הקישור הועתק"
Add it to the en.json

2022-01-03 08:00 UTC, maya-fisher commented on public/index.html
> +<body oncontextmenu="return false" >
Yes.

2022-01-03 08:03 UTC, maya-fisher commented on public/index.html
> +<body oncontextmenu="return false" >
Does not work when it's in the div.

2022-01-03 08:09 UTC, maya-fisher commented on src/components/buttons/CopyToClipboardButton.vue
> +        <img style="width: 20px; height: 20px" src="@/assets/icons/copylink.png" />
Done.

2022-01-03 08:17 UTC, maya-fisher commented on src/components/buttons/CopyToClipboardButton.vue
> +        <p class="button-text" v-if="!icon">{{ $t("buttons.CopyLink") }}</p>
I have a question about this.

2022-01-03 08:17 UTC, maya-fisher commented on src/components/buttons/CopyToClipboardButton.vue
> +import { isFolder } from "@/utils/isFolder";
Done

2022-01-03 08:20 UTC, maya-fisher commented on src/components/buttons/CopyToClipboardButton.vue
> +      else navigator.clipboard.writeText(`${window.location.origin}/file?id=${this.chosenFiles[0].id}`)
Done.

2022-01-03 08:43 UTC, maya-fisher commented on src/components/buttons/CopyToClipboardButton.vue
> +    },
Done

2022-01-03 08:45 UTC, maya-fisher commented on src/i18n/he.json
> +    "CopyToClipboard": "הקישור הועתק"
Done.

2022-01-09 12:09 UTC, yoavrozner requested changes
Good job @maya-fisher !
Please see my notes

2022-01-09 12:09 UTC, yoavrozner commented on src/components/buttons/CopyToClipboardButton.vue
> +        <p class="button-text" v-if="!icon">{{ $t("buttons.CopyLink") }}</p>
Please ask 🥇

2022-01-09 12:09 UTC, yoavrozner commented on src/components/buttons/CopyToClipboardButton.vue
> +import store from "@/store";
Default import comes first

2022-01-09 12:09 UTC, yoavrozner commented on src/components/buttons/CopyToClipboardButton.vue
> +      else navigator.clipboard.writeText(`${window.location.origin}/file?id=${fileId}`)
```suggestion
      const chosenFileType = this.chosenFiles[0].type;
      const url = `${window.location.origin}/${isFolder(chosenFileType) ? 'file' : 'folder'}?id=${fileId}`;
      navigator.clipboard.writeText(url)
```

2022-01-09 12:09 UTC, yoavrozner commented on src/utils/isSharedFile.js
> +}
No newline at end of file

2022-01-09 12:09 UTC, yoavrozner commented on src/utils/isSingleFile.js
> +}
```suggestion
}

```

2022-01-09 13:00 UTC, maya-fisher commented on src/components/buttons/CopyToClipboardButton.vue
> +import store from "@/store";
Done.

2022-01-09 13:21 UTC, maya-fisher commented on src/components/buttons/CopyToClipboardButton.vue
> +      else navigator.clipboard.writeText(`${window.location.origin}/file?id=${fileId}`)
Done.

2022-01-09 13:22 UTC, maya-fisher commented on src/utils/isSingleFile.js
> +}
Done.

2022-01-09 13:22 UTC, maya-fisher commented on src/utils/isSharedFile.js
> +}
Done.

2022-01-09 15:14 UTC, maya-fisher commented on src/components/buttons/CopyToClipboardButton.vue
> +        <p class="button-text" v-if="!icon">{{ $t("buttons.CopyLink") }}</p>
There is this check in almost all buttons components.
My questions is that almost all of the components of the buttons accept the icon as true, so I didn't understand what is it supposed to do. I believe that elsewhere in the ui there is a use for it, maybe you will know to tell me where exactly.

2022-01-10 14:20 UTC, yoavrozner commented on src/components/buttons/CopyToClipboardButton.vue
> +        <p class="button-text" v-if="!icon">{{ $t("buttons.CopyLink") }}</p>
I think we should look a this together for better insight for both of us

2022-01-10 14:21 UTC, yoavrozner approved these changes
@maya-fisher 🥇
Don't forget changelog.md

2022-01-11 09:05 UTC, yarinBenisty approved these changes
Good job @maya-fisher !

2022-01-11 09:09 UTC, maya-fisher commented on src/components/buttons/CopyToClipboardButton.vue
> +        <p class="button-text" v-if="!icon">{{ $t("buttons.CopyLink") }}</p>
Great

2022-01-16 11:31 UTC, merged