Fix: 503 bug
meateam/drive-ui pull request #148
Opened 2021-12-15 13:51 UTC by menachem554

2021-12-17 12:09 UTC, yarinBenisty approved these changes
Good job!

2021-12-19 11:26 UTC, maya-fisher approved these changes

2021-12-20 08:38 UTC, yoavrozner requested changes
Well done @menachem554 !
Please see my notes.

2021-12-20 08:38 UTC, yoavrozner commented on src/views/errors/503.vue
> +import router from '../../router/index';
1. Use the `@` for smarter folder navigation.
2. Take a look on the vue syntax `this.$router`.
3. Default imports comes before the non default import and not after.

2021-12-21 11:47 UTC, yoavrozner approved these changes
Well done!

2021-12-21 13:35 UTC, yarinBenisty approved these changes

2021-12-21 15:11 UTC, merged