Feat/save to mydrive
meateam/drive-ui pull request #150
Opened 2021-12-21 13:19 UTC by maya-fisher

2021-12-21 15:40 UTC, yoavrozner requested changes
Well done @maya-fisher !
Please see my notes

2021-12-21 15:40 UTC, yoavrozner commented on src/api/files.js
> +    }
Is this the real life? Is this just fantasy?

2021-12-21 15:40 UTC, yoavrozner commented on src/api/files.js
> +  }
```suggestion
  const [isExist, newFileName] = appendNumberIfFileExists({
    name: name,
    files: folders,
    loadingFiles: [],
  });

  return isExist ? newFileName : name; 
```

2021-12-21 15:40 UTC, yoavrozner commented on src/api/files.js
> +}
Missing newline

2021-12-21 15:40 UTC, yoavrozner commented on src/components/buttons/CopyFileButton.vue
> +import CopyFilePopup from "@/components/popups/CopyFilePopup";
Default imports comes first!

2021-12-21 15:40 UTC, yoavrozner commented on src/components/buttons/CopyFileButton.vue
> +  },
Redundant

2021-12-21 15:40 UTC, yoavrozner commented on src/components/buttons/CopyFileButton.vue
> +      return this.chosenFiles.every((file) => !isFolder(file.type)) ? true : false;
```suggestion
      return this.chosenFiles.every((file) => !isFolder(file.type));
```

2021-12-21 15:40 UTC, yoavrozner commented on src/components/buttons/CopyFileButton.vue
> +      return this.chosenFiles.every((file) => !isFolder(file.type)) ? true : false;
Like every! well done!

2021-12-21 15:40 UTC, yoavrozner commented on src/components/buttons/CopyFileButton.vue
> +      return this.chosenFiles.every((file) => !isFolder(file.type)) ? true : false;
&& is single file

2021-12-21 15:40 UTC, yoavrozner commented on src/components/buttons/CopyFileButton.vue
> +          this.$router.push("/my-drive")
So help me G*d

2021-12-21 15:40 UTC, yoavrozner commented on src/components/buttons/CopyFileButton.vue
> +        !this.isFileReadOnly()
Put it in the utils

2021-12-21 15:40 UTC, yoavrozner commented on src/components/buttons/CopyFileButton.vue
> +</script>
New line

2021-12-21 15:40 UTC, yoavrozner commented on src/components/popups/CopyFilePopup.vue
> +    },
One function to rule them all

2021-12-21 15:40 UTC, yoavrozner commented on src/components/popups/CopyFilePopup.vue
> +        this.currentChildren = await filesApi.getFoldersByFolder(parent ? parent.id : undefined);
?

2021-12-21 15:40 UTC, yoavrozner commented on src/components/popups/CopyFilePopup.vue
> +          });
Switch case with enum

2021-12-21 15:40 UTC, yoavrozner commented on src/components/popups/CopyFilePopup.vue
> +      this.folderDest = folder;
Switch case

2021-12-21 15:40 UTC, yoavrozner commented on src/store/modules/files.js
>    async addFav({dispatch }, file) {
```suggestion
  async addFav({ dispatch }, file) {
```

2021-12-21 16:14 UTC, maya-fisher commented on src/api/files.js
>  import store from "@/store";
Done

2021-12-21 16:15 UTC, maya-fisher commented on src/api/files.js
> +  return res;
Done

2021-12-21 16:15 UTC, maya-fisher commented on src/api/files.js
> +    }
fantasy

2021-12-21 16:16 UTC, maya-fisher commented on src/api/files.js
> +  }
Done

2021-12-21 16:16 UTC, maya-fisher commented on src/api/files.js
> +}
Done

2021-12-21 16:17 UTC, maya-fisher commented on src/components/buttons/CopyFileButton.vue
> +import CopyFilePopup from "@/components/popups/CopyFilePopup";
Done

2021-12-21 16:17 UTC, maya-fisher commented on src/components/buttons/CopyFileButton.vue
> +  },
Done

2021-12-21 16:19 UTC, maya-fisher commented on src/components/buttons/CopyFileButton.vue
> +      return this.chosenFiles.every((file) => !isFolder(file.type)) ? true : false;
Done

2021-12-21 16:19 UTC, maya-fisher commented on src/components/buttons/CopyFileButton.vue
> +      return this.chosenFiles.every((file) => !isFolder(file.type)) ? true : false;
Thanks! I think I copied this from favorites

2021-12-21 16:20 UTC, maya-fisher commented on src/components/buttons/CopyFileButton.vue
> +          this.$router.push("/my-drive")
:(

2021-12-21 16:31 UTC, maya-fisher commented on src/components/buttons/CopyFileButton.vue
> +        !this.isFileReadOnly()
I forgot it's not necessary here at all

2021-12-21 16:31 UTC, maya-fisher commented on src/components/buttons/CopyFileButton.vue
> +</script>
Done

2021-12-21 18:12 UTC, maya-fisher commented on src/components/popups/CopyFilePopup.vue
> +    },
Done

2021-12-21 18:16 UTC, maya-fisher commented on src/components/popups/CopyFilePopup.vue
> +          });
Done

2021-12-21 18:16 UTC, maya-fisher commented on src/components/popups/CopyFilePopup.vue
> +      this.folderDest = folder;
Done

2021-12-21 18:17 UTC, maya-fisher commented on src/store/modules/files.js
>    async addFav({dispatch }, file) {
Done

2021-12-21 18:19 UTC, maya-fisher commented on src/components/popups/CopyFilePopup.vue
> +        this.currentChildren = await filesApi.getFoldersByFolder(parent ? parent.id : undefined);
To copy a file into shared with me, you have to select a folder.

2021-12-21 18:20 UTC, maya-fisher commented on src/components/popups/CopyFilePopup.vue
> +        this.currentChildren = await filesApi.getFoldersByFolder(parent ? parent.id : undefined);
If there is something else that is wrong then what it is?

2022-01-09 11:58 UTC, yoavrozner reviewed
Well done @maya-fisher !
Please see my notes

2022-01-09 11:58 UTC, yoavrozner commented on src/api/files.js
> +    }
```suggestion
    if (folderID == undefined) {
      const [file, folderFiles] = await Promise.all([getFileByID(fileID), fetchFiles()]);
      return await getNewFileName(file.name, folderFiles);
    } else {
      const folder = await getFileByID(folderID);
      const [file, folderFiles] = await Promise.all([getFileByID(fileID), fetchFiles(folder)]);
      return await getNewFileName(file.name, folderFiles);
    }
```

2022-01-09 11:58 UTC, yoavrozner commented on src/api/files.js
> +  let [isExist, newFileName] = appendNumberIfFileExists({
```suggestion
  const [isExist, newFileName] = appendNumberIfFileExists({
```

2022-01-09 11:58 UTC, yoavrozner commented on src/components/buttons/CopyFileButton.vue
> +      }
The indentations are not equal

2022-01-09 12:49 UTC, maya-fisher commented on src/api/files.js
> +    }
Ok.

2022-01-09 12:50 UTC, maya-fisher commented on src/api/files.js
> +  let [isExist, newFileName] = appendNumberIfFileExists({
Done.

2022-01-09 12:56 UTC, maya-fisher commented on src/components/buttons/CopyFileButton.vue
> +      }
I didn't understand what you meant.

2022-01-10 14:09 UTC, maya-fisher commented on docker-compose.yml
> +    image: "drivehub.azurecr.io/meateam/api-gateway:save-to-mydrive"
Done. But need to push to drivehub the updated image

2022-01-10 14:14 UTC, yoavrozner approved these changes
💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯

2022-01-10 14:15 UTC, yoavrozner commented on src/components/buttons/CopyFileButton.vue
> +      }
בעברית, ההזחה שלך לא שווה בין התנאי והתנאי השני

2022-01-10 14:18 UTC, yoavrozner commented on docker-compose.yml
> +    image: "drivehub.azurecr.io/meateam/api-gateway:save-to-mydrive"
In the ui we have ci that auto pushes the new image to the drivehub

2022-01-11 09:13 UTC, yarinBenisty approved these changes

2022-01-19 11:06 UTC, merged