Feature/keyboard shortcuts
meateam/drive-ui pull request #155
Opened 2022-02-09 10:49 UTC by sternomer

2022-02-09 11:08 UTC, sternomer commented on src/store/modules/loading.js
> +  popupStatus: false,
better name: isPopupOpen

2022-02-09 11:25 UTC, sternomer commented on src/components/popups/share-popup/SharePopup.vue
> +      if (!this.$store.getters.popupStatus) {
```suggestion
      if (this.$store.getters.popupStatus) {
          return;
      }
```

2022-02-09 11:57 UTC, sternomer reviewed
Check again if there are more popups that need to watch for "dialog" changes (not open when others are open) example: CreateFilePopup

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/share-popup/SharePopup.vue
> +      if (!this.$store.getters.popupStatus) {
fix formatting

```suggestion
      if (this.$store.getters.popupStatus) {
          return
      }
```

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/share-popup/SharePopup.vue
> +        this.$store.commit('changePopupStatus')
move this to watch

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/share-popup/SharePopup.vue
> +        this.$store.commit('changePopupStatus')
move this out of the if (so it works for both open and close)

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/info-popup/BaseInfoPopup.vue
> +        this.$store.commit('changePopupStatus')
same

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/info-popup/BaseInfoPopup.vue
> +      if (!this.$store.getters.popupStatus) {
same

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/info-popup/BaseInfoPopup.vue
> +        this.$store.commit('changePopupStatus')
same

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/external-transfer-popup/ExternalTransferPopup.vue
> +      if (!this.$store.getters.popupStatus) {
same

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/external-transfer-popup/ExternalTransferPopup.vue
> +      if (!val) {
same

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/Preview.vue
> +      if (!this.$store.getters.popupStatus) {
same

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/Preview.vue
> +      if (!val) {
same

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/MoveToPopup.vue
> +      if (!this.$store.getters.popupStatus) {
same

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/MoveToPopup.vue
> +        this.$store.commit('changePopupStatus')
same

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/BaseNamePopup.vue
> +      if (!this.$store.getters.popupStatus) {
same

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/BaseNamePopup.vue
> +      if (!val) {
same

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/BaseAlertPopup.vue
> +      if (!this.$store.getters.popupStatus) {
same

2022-02-09 11:57 UTC, sternomer commented on src/components/popups/BaseAlertPopup.vue
> +        this.$store.commit('changePopupStatus')
same

2022-02-10 15:54 UTC, MichaelSimkin requested changes
Looks good. 
One last thing: I think the store functions for the popup logic don't belong in the "loading" store. You should create a new store for them.

2022-02-14 09:33 UTC, MichaelSimkin approved these changes

2022-02-15 09:35 UTC, merged