Feature/convert docs #22
meateam/drive-ui pull request #23
Opened 2020-09-23 11:19 UTC by yosef32

2020-09-23 13:01 UTC, nogahaskal requested changes
Looks good :+1: 
please tell me when you finish so I can check it again.
Also,
please put that in kubernetes.

2020-09-23 13:01 UTC, nogahaskal commented on src/components/popups/BaseAlertPopup.vue
> +  name: "BaseAlertPopup",
The base word is used only in the name of the file to show that this is a generic stupid components. In the name you can remove that.

2020-09-24 06:58 UTC, yosef32 commented on src/components/buttons/DeleteButton.vue
> +      @ok="onDelete"
done

2020-09-24 06:58 UTC, yosef32 commented on src/components/files/list/FileTable.vue
> +      @ok="onConvert(chosenFiles[0])"
done

2020-09-24 06:58 UTC, yosef32 commented on src/components/files/list/FileTable.vue
> +      } else if (this.isOldOffice(file)) {
done

2020-09-24 06:58 UTC, yosef32 commented on src/components/files/preview/FilesPreview.vue
> +      @ok="onConvert(chosenFiles[0])"
done

2020-09-24 07:02 UTC, yosef32 commented on src/components/files/list/FileTable.vue
> +        this.$refs.popup.open()
done

2020-09-24 07:02 UTC, yosef32 commented on src/components/files/preview/FilesPreview.vue
> +      ref="popup"
done

2020-09-24 19:03 UTC, nogahaskal requested changes
One last thing :)

2020-11-12 08:30 UTC, yosef32 commented on src/components/files/list/FileTable.vue
> +      selectedFile: undefined,
done

2020-11-12 14:00 UTC, Shahar-Y commented
@nogahaskal comment if something else is required, and approve if not.
@yosef32 deploy to k8s and add a link in the description so everyone could look at the changes

2020-11-23 07:09 UTC, nogahaskal requested changes
Looks good. please add changelog and fix the comment.

2020-11-23 07:09 UTC, nogahaskal commented on src/components/files/list/FileTable.vue
> +    convertMessage(file) {
Maybe you should create this function in the utils because it repeats in more then one file. 
Also, if I were you, I would use in the parameter only the type. you don't need all the file, it's just makes you add the if(file), that not necessary.

2020-11-29 07:50 UTC, nogahaskal approved these changes

2020-11-30 12:45 UTC, merged