feat: add approverInfo
meateam/drive-ui pull request #40
Opened 2020-11-10 09:11 UTC by nogahaskal

2020-11-12 06:54 UTC, Shahar-Y requested changes
1. Was it tested? and how? 
2. Does it affect other services?
3. Add a changelog.
4. Link to the deployment it was tested on.
Add all of this information in the PR description

2020-11-12 06:54 UTC, Shahar-Y commented on docker-compose.yml
> +    image: "drivehub.azurecr.io/meateam/user-service:approverInfo"
Use a version

2020-11-15 14:06 UTC, nogahaskal commented on docker-compose.yml
> +    image: "drivehub.azurecr.io/meateam/user-service:approverInfo"
done.

2020-11-15 20:55 UTC, Shahar-Y approved these changes

2020-12-09 11:29 UTC, Shahar-Y requested changes
Add a description and a link to the environment it was tested on

2020-12-09 11:29 UTC, Shahar-Y commented on CHANGELOG.md
> +- info about the approvers in the ui.
Add a link to the PR, describe if major/minor/hotfix

2020-12-09 11:29 UTC, Shahar-Y commented on CHANGELOG.md
> +## [v2.1.0]
Those versions do not exist on github as versions. not related to the PR bot needs fixing

2020-12-09 11:29 UTC, Shahar-Y commented on docker-compose.yml
> +    image: "drivehub.azurecr.io/meateam/api-gateway:approverInfo"
this tag should not exist in develop.

2020-12-09 11:29 UTC, Shahar-Y commented on docker-compose.yml
> +    image: "drivehub.azurecr.io/meateam/user-service:approverInfo"
mm.. not done?

2020-12-09 11:29 UTC, Shahar-Y commented on src/components/popups/external-transfer-popup/steps/Approval.vue
> +        }
What if (canApproveToUser && !cantApproveReasons)  ? shouldn't there be a default?

2020-12-09 11:29 UTC, Shahar-Y commented on src/i18n/he.json
> +      "OpenInTomy": "לפתיחת תקלה"
Do these exist in the english version?

2021-02-01 15:10 UTC, merged