Featue/pagination
meateam/drive-ui pull request #47
Opened 2020-11-29 08:02 UTC by nogahaskal

Create server file pagination for shared files. 
Make users call more efficient using dictionary.

2020-11-29 14:17 UTC, Shahar-Y requested changes

2020-11-29 14:17 UTC, Shahar-Y commented on docker-compose.yml
> -    image: "drivehub.azurecr.io/meateam/permission-service:v2.0.0"
change this

2020-11-29 14:17 UTC, Shahar-Y commented on src/api/files.js
> +  const res = await Axios.get(`${baseURL}/api/files?shares&appId=drive&pageSize=10&pageNum=${pageNum}`);
change pageSize to const

2020-11-29 14:17 UTC, Shahar-Y commented on src/api/files.js
> +  const res = await Axios.get(`${baseURL}/api/files?shares&appId=dropbox&pageSize=10&pageNum=${pageNum}`);
change pageSize to const

2020-11-29 14:17 UTC, Shahar-Y commented on src/components/files/list/FileTable.vue
> +      itemsPerPage: 10,
should also be the same const from the config

2020-11-29 14:17 UTC, Shahar-Y commented on src/store/modules/files.js
> +        formattedFile.owner = isOwner ? "אני" : await getFileOwnerName(file.ownerId);
I'd prefer there won't be hebrew in the code

2020-11-29 14:17 UTC, Shahar-Y commented on src/store/modules/search.js
> +          formattedFile.owner = isOwner ? "אני" : await getFileOwnerName(file.ownerId);
hebrew

2020-11-29 14:17 UTC, Shahar-Y commented
Also, update the CHANGELOG.md

2020-12-09 11:46 UTC, Shahar-Y commented
@nogahaskal please refer to the cr

2020-12-20 08:41 UTC, nogahaskal commented on src/api/files.js
> +  const res = await Axios.get(`${baseURL}/api/files?shares&appId=drive&pageSize=10&pageNum=${pageNum}`);
done.

2020-12-20 08:41 UTC, nogahaskal commented on docker-compose.yml
> -    image: "drivehub.azurecr.io/meateam/permission-service:v2.0.0"
done.

2020-12-20 08:41 UTC, nogahaskal commented on src/api/files.js
> +  const res = await Axios.get(`${baseURL}/api/files?shares&appId=dropbox&pageSize=10&pageNum=${pageNum}`);
done.

2020-12-20 08:42 UTC, nogahaskal commented on src/components/files/list/FileTable.vue
> +      itemsPerPage: 10,
done.

2020-12-20 08:53 UTC, nogahaskal commented on src/store/modules/files.js
> +        formattedFile.owner = isOwner ? "אני" : await getFileOwnerName(file.ownerId);
I have problem to use in this file the i18n because it's a simple js that doesn't include the vue interface.

2020-12-20 14:41 UTC, Shahar-Y approved these changes

2021-01-13 13:28 UTC, merged