Fix/fetch shared files
meateam/drive-ui pull request #49
Opened 2020-12-10 14:33 UTC by nettashviro

fix the fetching of getSharedFIles. related to pr #204

2020-12-13 10:37 UTC, Shahar-Y commented on CHANGELOG.md
> +- fix fetch shared files bug.
```suggestion
- hotfix: ([49](https://github.com/meateam/drive-ui/pull/49/)) : fix fetch shared files bug.
```

2020-12-13 10:38 UTC, Shahar-Y requested changes
Just commit the change and it's approved

2020-12-13 11:12 UTC, nettashviro commented on CHANGELOG.md
> +- fix fetch shared files bug.
done

2020-12-13 11:13 UTC, nettashviro commented
> Just commit the change and it's approved

changed Changelog file, please approve the pr :)

2020-12-13 11:38 UTC, Shahar-Y approved these changes

2021-05-24 11:02 UTC, Shahar-Y requested changes
Did you test to see what happens when some of the files do fail? 
Is there no different error handling for that case? And if all fail, what error is presented?

2021-05-24 12:32 UTC, yoavrozner approved these changes
Good job!

2021-06-20 08:49 UTC, nettashviro commented
> Did you test to see what happens when some of the files do fail?
> Is there no different error handling for that case? And if all fail, what error is presented?

I checked all the end cases, when one file fails a corresponding error returns and it returns within the array of failed files.

2021-06-20 11:17 UTC, Shahar-Y requested changes
I see you have conflicts in files.js

2021-06-20 11:17 UTC, Shahar-Y commented on CHANGELOG.md
> +
um... unreleased?

2021-06-21 09:01 UTC, nettashviro commented on CHANGELOG.md
> +
that's what happend when you work with this shitty changelog lol

2021-06-23 07:57 UTC, Shahar-Y commented on CHANGELOG.md
> +
All shall be done by the CHANGELOG policy!

2021-06-23 07:58 UTC, Shahar-Y approved these changes

2021-07-01 12:42 UTC, merged