Feature/upload folder
meateam/drive-ui pull request #56
Opened 2021-01-19 09:03 UTC by yosef32

2021-04-20 08:09 UTC, yoavrozner requested changes
Great job Yosef!
I enjoy reading your code.

2021-04-20 08:09 UTC, yoavrozner commented on src/utils/drop.js
> +    for (const p of promises) {
Promise.all is the best thing after sports day

2021-04-20 08:09 UTC, yoavrozner commented on src/utils/drop.js
> +        return await store.dispatch(UploadAction.uploadFileToFolder, {
You don't the `await` here.

2021-04-20 08:09 UTC, yoavrozner commented on src/utils/drop.js
> +                isFirstFolder = !isFirstFolder;
I think `isFirstFolder = false` would be better for readability

2021-04-20 08:09 UTC, yoavrozner commented on src/utils/drop.js
> +                await getEntries(e, res, isFirstFolder)
Promise.all

2021-04-20 08:09 UTC, yoavrozner commented on src/utils/drop.js
> +    return await new Promise((resolve, reject) => fileEntry.file(resolve, reject));
`await` is not needed here

2021-04-20 08:23 UTC, yosef32 commented on src/App.vue
> +  created() {
done

2021-04-20 08:26 UTC, yosef32 commented on src/App.vue
> +    window.addEventListener("beforeunload", this.close);
That's why I put it in the APP because it happens once in every tab creation

2021-04-20 08:27 UTC, yosef32 commented on src/App.vue
> +      console.log(this.isUpload);
done

2021-04-22 12:27 UTC, Shahar-Y requested changes

2021-04-22 12:27 UTC, Shahar-Y commented on src/store/modules/files.js
> +const ownerMy = "אני";
```suggestion
const hebrewMe = "אני";
```

2021-04-22 12:27 UTC, Shahar-Y commented on src/store/modules/files.js
> +const MB5 = 5 << 20
```suggestion
const MB = 1024 * 1024;
```

2021-04-22 12:27 UTC, Shahar-Y commented on src/store/modules/files.js
> +    if (file.size <= MB5) {
```suggestion
    if (file.size <= 5 * MB) {
```

2021-04-22 12:27 UTC, Shahar-Y commented on src/store/modules/upload.js
> +const MB5 = 5 << 20
If those are repetitive, I'd put them in a single shared file

2021-04-22 12:27 UTC, Shahar-Y commented on src/store/modules/upload.js
> +  async [UploadAction.uploadFileToFolder]({ commit }, folderAndFile) {
Why is it in an array? And why receive an object for a single parameter?
Also, update the `@param` explanation and make sure it is correct in all other functions

2021-04-22 12:27 UTC, Shahar-Y commented on src/store/modules/upload.js
> +            progress: Math.round((100 * event.loaded) / event.total),
This line is repetitive. Export it from a single file

2021-04-22 12:27 UTC, Shahar-Y commented on src/store/modules/upload.js
> +    ) throw new Error("שם התיקייה כבר קיים בתיקייה הנוכחית");
i18n

2021-04-22 12:27 UTC, Shahar-Y commented on src/store/modules/upload.js
> +import * as filesApi from "@/api/files";
Is it only for uploading a folder? If so, rename the file to `uploadFolder.js`

2021-04-22 12:27 UTC, Shahar-Y commented on src/store/modules/upload.js
> +import * as filesApi from "@/api/files";
Also, add a description at the beginning of the file for the purpose of the file and it's uses

2021-04-22 12:27 UTC, Shahar-Y commented on src/utils/drop.js
> +import store from '@/store'
Add a description at the beginning of the file for the purpose of the file and it's uses

2021-04-22 12:27 UTC, Shahar-Y commented on src/utils/lastUpdatedFileHandler.js
> +      const file = await filesApi.getFileByID(fileID, false).catch(() => undefined);
What does the `false` mean?

2021-06-07 07:04 UTC, yoavrozner requested changes
Add async mapper with 3 promises max

2021-06-14 09:12 UTC, yoavrozner commented on src/App.vue
> +    window.addEventListener("beforeunload", this.close);
@yosef32 what about it?

2021-06-14 09:27 UTC, yoavrozner requested changes
Great job! What is barak.zip file?

2021-06-15 08:00 UTC, Shahar-Y approved these changes

2021-06-15 08:01 UTC, merged