WIP: Feat/add cts intergation
meateam/drive-ui pull request #67
Opened 2021-03-07 13:36 UTC by nettashviro

Change stepper in new external share
add unfolding tab for external shares

2021-03-07 18:15 UTC, Shahar-Y requested changes
Address the comments, mainly small things. 
In the future, PLEASE use the linter as a separated PR. This was pure pain to watch the differences.
All in all, great job :+1:

2021-03-07 18:15 UTC, Shahar-Y commented on src/components/popups/external-transfer-popup/ExternalTransferPopup.vue
> +        destination: this.externalNetworkDest, // TODO: CHANGE TO APP ID
Is it still on the TODO list?

2021-03-07 18:15 UTC, Shahar-Y commented on src/components/popups/external-transfer-popup/steps/Approval.vue
> +    <!-- if the user has no unit and he isnt approver -->
Good job with the comments :+1:

2021-03-07 18:15 UTC, Shahar-Y commented on src/i18n/en.json
> +    "StatusTransferd": "Status files transferd",
Transferred*
Change across the code with ctrl+f

2021-03-07 18:15 UTC, Shahar-Y commented on src/i18n/he.json
> +    "ExternalShareFailed": "שיתופים חיצוניים שלא התקבלו"
Add in english

2021-03-07 18:15 UTC, Shahar-Y commented on src/i18n/he.json
> +    "Approval": "מאשרים",
Add in english

2021-03-07 18:15 UTC, Shahar-Y commented on src/i18n/he.json
> +    "HeaderDestTomcal": "תומכל",
Add in english

2021-03-07 18:15 UTC, Shahar-Y commented on src/i18n/he.json
> +    "DisableClassification": "לא ניתן להעביר קבצים בסיווג {classificationName}",
Add in english

2021-03-07 18:15 UTC, Shahar-Y commented on src/store/modules/auth.js
> +    await Promise.all(
:+1:

2021-03-07 18:15 UTC, Shahar-Y commented on src/store/modules/configuration.js
> +      isDefault: false,
At least change the default to `appId2` :grimacing:

2021-03-07 18:15 UTC, Shahar-Y commented on src/store/modules/files.js
> +      commit('setServerFilesLength', permissions.itemCount);
WHY WOULD YOU DO THIS TO MEEEE

2021-03-07 18:15 UTC, Shahar-Y commented on src/store/modules/files.js
> +      dispatch('onError', err);
MY EYES HURT

2021-03-09 14:27 UTC, nettashviro commented on src/store/modules/files.js
> +      commit('setServerFilesLength', permissions.itemCount);
I did not notice to the prettier settings, is auto-save.
But deep down it's funny :satisfied:

2021-03-09 14:29 UTC, nettashviro commented on src/store/modules/files.js
> +      dispatch('onError', err);
Then close your eyes :see_no_evil:

2021-03-09 14:30 UTC, nettashviro commented on src/i18n/he.json
> +    "DisableClassification": "לא ניתן להעביר קבצים בסיווג {classificationName}",
donnneeee

2021-03-09 14:30 UTC, nettashviro commented on src/components/layout/sidenav/Sidenav.vue
> +        </router-link> -->
done, waited for this page to actually work

2021-03-09 14:33 UTC, nettashviro commented on src/api/share.js
> +
done

2021-03-09 14:35 UTC, nettashviro commented
> Address the comments, mainly small things.
> In the future, PLEASE use the linter as a separated PR. This was pure pain to watch the differences.
> All in all, great job

glad you enjoyed

2021-03-09 14:36 UTC, nettashviro commented on docker-compose.yml
> +  #     - elasticsearch
myyyyy computtteerrr was stuck from the kibana :(

2021-03-09 14:40 UTC, nettashviro commented on src/components/popups/external-transfer-popup/ExternalTransferPopup.vue
> +        destination: this.externalNetworkDest, // TODO: CHANGE TO APP ID
nope

2021-03-23 09:35 UTC, Shahar-Y commented on src/store/modules/files.js
> +      dispatch('onError', err);
:cry:

2021-03-23 09:36 UTC, Shahar-Y requested changes
Just change the `transferd` to `transferred` with ctrl + f

done

2021-03-23 09:56 UTC, nettashviro commented
> Just change the `transferd` to `transferred` with ctrl + f

done

2021-03-23 11:00 UTC, Shahar-Y approved these changes

2021-03-25 14:09 UTC, merged