WIP: add pagination in files items view
meateam/drive-ui pull request #73
Opened 2021-04-08 13:22 UTC by nettashviro

2021-05-20 12:28 UTC, yoavrozner requested changes

2021-05-20 12:28 UTC, yoavrozner commented on src/api/files.js
> +  const permissions = res.data.files.filter((item) => item.type == fileTypes.folder);
```suggestion
  const permissions = res.data.files.filter((item) => isFolder(item.type));
```

2021-05-20 13:16 UTC, nettashviro commented on src/api/files.js
> +  const permissions = res.data.files.filter((item) => item.type == fileTypes.folder);
done :)

2021-05-20 13:52 UTC, yoavrozner requested changes
Well done!

2021-05-20 13:52 UTC, yoavrozner commented on src/components/files/preview/FilesPreview.vue
> +      const filesElm = document.querySelector("#files-items-pagination");
I don't like it. Vue should have this kind of stuff

2021-05-20 13:52 UTC, yoavrozner commented on src/components/popups/info-popup/BaseInfoPopup.vue
> +        getExternalPermissions(this.file.id).catch(() => (externalPermissionsRes = [])),
Is it working on failure?

2021-05-20 13:52 UTC, yoavrozner commented on src/components/popups/info-popup/BaseInfoPopup.vue
> +        .filter((user, index, self) => index === self.indexOf(user.id));
Are you sure it is working well?

2021-05-20 13:52 UTC, yoavrozner commented on src/views/SharedWithMe.vue
> +      return fileView == 0 || fileView == "undefined" || fileView == undefined ? pageSize : pageSize * 2;
`fileView == "undefined" || fileView == undefined` don't you have a better way?

2021-05-20 13:52 UTC, yoavrozner commented on src/views/SharedWithMe.vue
> +      return fileView == 0 || fileView == "undefined" || fileView == undefined ? pageSize : pageSize * 2;
`fileView === 0`

2021-05-20 14:28 UTC, nettashviro commented on src/views/SharedWithMe.vue
> +      return fileView == 0 || fileView == "undefined" || fileView == undefined ? pageSize : pageSize * 2;
how? it's different types

2021-05-20 14:28 UTC, nettashviro commented on src/views/SharedWithMe.vue
> +      if (oldValue != newValue) {
done

2021-05-20 14:39 UTC, nettashviro commented on src/components/popups/info-popup/BaseInfoPopup.vue
> +        getExternalPermissions(this.file.id).catch(() => (externalPermissionsRes = [])),
done

2021-05-20 14:44 UTC, nettashviro commented on src/components/files/preview/FilesPreview.vue
> +      const filesElm = document.querySelector("#files-items-pagination");
odne

2021-05-23 11:14 UTC, Shahar-Y approved these changes
Needs to be approved by @yoavrozner

2021-05-24 12:06 UTC, yoavrozner reviewed
Great job @nettashviro !
Please see my notes :)

2021-05-24 12:06 UTC, yoavrozner commented on src/components/files/preview/FilesPreview.vue
> +    if (!this.isListenerAttached) {
?

2021-05-24 12:06 UTC, yoavrozner commented on src/components/popups/info-popup/BaseInfoPopup.vue
> +        });
Wouldn't `map` or `reduce` fit better here?

2021-05-24 12:09 UTC, yoavrozner commented on src/views/SharedWithMe.vue
> +      return fileView == 0 || fileView == "undefined" || fileView == undefined ? pageSize : pageSize * 2;
Uncaught TypeError: Cannot read property 'undefined' of null

2021-05-31 12:06 UTC, nettashviro commented on src/components/popups/info-popup/BaseInfoPopup.vue
> +        });
done

2021-05-31 14:23 UTC, yoavrozner approved these changes
Well done! @nettashviro

2021-05-31 14:23 UTC, yoavrozner commented on src/components/popups/info-popup/BaseInfoPopup.vue
> +        const [externalUsersFailed, externalUsers] = _.partition(externalPermissionsRes, function(externalPermission) {
Big like. I like this implementation. Thanks

2021-06-14 11:36 UTC, merged