fix: add validation to search by mail or t and show all external tran…
meateam/drive-ui pull request #85
Opened 2021-05-06 07:52 UTC by yoavrozner

…sffers in the sidenav

2021-05-06 08:52 UTC, nettashviro requested changes
very nice implementation!

2021-05-06 08:52 UTC, nettashviro commented on src/components/inputs/BaseAutocomplete.vue
> +      <p id="no-resault">{{ $t(`autocomplete.${ validationFailedMsg ? validationFailedMsg : noResult || 'NoResult'}`)}}</p>
typo
```suggestion
      <p id="no-result">{{ $t(`autocomplete.${ validationFailedMsg ? validationFailedMsg : noResult || 'NoResult'}`)}}</p>
```

2021-05-06 08:52 UTC, nettashviro commented on src/i18n/he.json
> +    "Users": "הוסיפו אנשים...",
add in english version

2021-05-06 08:52 UTC, nettashviro commented on src/components/popups/share-popup/tabs/Share.vue
> +      return validationAdvancedSearchFactory(AdvancedSearchToEnum(this.advancedSearchSelection));
very nice! tell to alexa that you have won

2021-05-06 08:52 UTC, nettashviro commented on src/utils/advancedSearchValidation.js
> +            return () => null;
why this and the default case if they has the same results?

2021-05-09 07:14 UTC, yoavrozner commented on src/components/popups/share-popup/tabs/Share.vue
> +      return validationAdvancedSearchFactory(AdvancedSearchToEnum(this.advancedSearchSelection));
Hahahaha :100:

2021-05-09 07:16 UTC, yoavrozner commented on src/utils/advancedSearchValidation.js
> +            return () => null;
Because it might change soon to a different validation function. Do you think I should remove it?

2021-05-09 07:25 UTC, nettashviro commented on src/utils/advancedSearchValidation.js
> +            return () => null;
yep

2021-05-09 07:33 UTC, nettashviro approved these changes

2021-05-09 07:49 UTC, merged